<?php
session_start();

/** * We capture the new 'athlete_category' and 'sport' fields 
 * generated by the dynamic dropdowns and JS logic.
 */
$_SESSION['reg_data'] = $_POST;

// Standardizing the fee logic based on your existing structure
$amount = ($_POST['fee_type'] == 'ration') ? 500 : 1000;

// Placeholder for your Razorpay Key
$api_key = "YOUR_RAZORPAY_KEY"; 
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Securing Payment Gateway...</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
</head>
<body class="bg-slate-900 flex items-center justify-center h-screen">

    <div class="text-center animate__animated animate__fadeIn">
        <div class="inline-block w-16 h-16 border-4 border-orange-600 border-t-transparent rounded-full animate-spin mb-6"></div>
        <h2 class="text-white font-black uppercase italic tracking-widest text-xl">Connecting to Gateway</h2>
        <p class="text-gray-400 text-xs mt-2 uppercase">Please do not refresh or close this window...</p>
        
        <div class="mt-8 bg-white/5 p-4 rounded border border-white/10">
            <p class="text-gray-400 text-[10px] uppercase font-bold">Athlete: <?php echo htmlspecialchars($_POST['fullname']); ?></p>
            <p class="text-orange-500 text-[10px] uppercase font-bold">Category: <?php echo htmlspecialchars($_POST['athlete_category']); ?></p>
        </div>
    </div>

    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        "key": "<?php echo $api_key; ?>", 
        "amount": "<?php echo $amount * 100; ?>", // Amount in paise
        "currency": "INR",
        "name": "Firozabad Sports Academy",
        "description": "Registration Fee - <?php echo $_POST['athlete_category']; ?>",
        "image": "assets/images/logo.png", // Path to your logo
        "handler": function (response){
            // Redirecting to success page to save data to DB and generate UID
            window.location.href = "payment_success.php?pay_id=" + response.razorpay_payment_id;
        },
        "prefill": {
            "name": "<?php echo $_POST['fullname']; ?>",
            "email": "<?php echo $_POST['email']; ?>",
            "contact": "<?php echo $_POST['mobile']; ?>"
        },
        "theme": { 
            "color": "#001e5f" // Navy Blue branding
        },
        "modal": {
            "ondismiss": function(){
                // If user cancels, send them back to registration with a warning
                window.location.href = "registration.php?status=cancelled";
            }
        }
    };
    var rzp1 = new Razorpay(options);
    
    // Automatically open Razorpay on page load
    window.onload = function() {
        rzp1.open();
    };
    </script>
</body>
</html>